{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
  namespace: {{ .Values.httproute.namespace }}
spec:
  hostnames:
    - {{ .Values.httproute.hostname }}
  parentRefs:
    - name: {{ .Values.httproute.gateway.name }}
      namespace: {{ .Values.httproute.gateway.namespace }}
      sectionName: {{ .Values.httproute.gateway.sectionName }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.httproute.path }}
      backendRefs:
        - name: {{ .Values.httproute.backend.name }}
          port: {{ .Values.httproute.backend.port }}
{{- end }}
