{{- if .Values.externalSecrets.enabled }}
{{- if .Values.externalSecrets.items }}
  {{- range .Values.externalSecrets.items }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: {{ .name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: opaque
      data: 
        {{- range $key, $value := .templateData }}
        {{ $key }}: '{{ `{{ .` }}{{ $value }}{{ ` }}` }}'
        {{- end }}
  data:
    {{- range .data }}
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .remoteKey }}
        metadataPolicy: None
      secretKey: {{ .secretKey }}
    {{- end }}
  {{- end }}
{{- else }}