replicaCount: 3
image:
  repository: emqx/emqx
  pullPolicy: IfNotPresent
  tag: ""

podManagementPolicy: Parallel

persistence:
  enabled: true
  size: 10Gi
  storageClassName: "longhorn"
  accessMode: ReadWriteOnce

emqxConfig:
  EMQX_CLUSTER__DISCOVERY_STRATEGY: "dns"

externalSecrets:
  enabled: true
  items:
  - name: emqx-basic-auth
    templateData:
      EMQX_DASHBOARD__DEFAULT_USERNAME: 'admin'
      EMQX_DASHBOARD__DEFAULT_PASSWORD: password
    data:
    - remoteKey: emqx-dashboard-password
      secretKey: password

envFromSecret: "emqx-basic-auth"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  clusterIP: None
  mqtt: 1883
  mqttssl: 8883
  ws: 8083
  wss: 8084
  dashboard: 18083
  externalTrafficPolicy: "Cluster"

httproutes:
- enabled: true
  name: emqx-dashboard-httproute
  namespace: emqx
  hostname: dashboard-emqx.svc.damman.tech
  gateway:
    name: svc-gateway
    namespace: kube-system
    sectionName: svc-https-listener
  path: /
  backend:
    name: emqx
    port: 18083

metrics:
  enabled: false
  type: prometheus
