{{- range .Values.httproutes }}
{{- if .enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  hostnames:
    - {{ .hostname }}
  parentRefs:
    - name: {{ .gateway.name }}
      namespace: {{ .gateway.namespace }}
      sectionName: {{ .gateway.sectionName }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .path }}
      backendRefs:
        - name: {{ .backend.name }}
          port: {{ .backend.port }}
{{- end }}
{{- end }}
