image:
  registry: "docker.io"
  repository: "mariadb"
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 3306
  nodePort:
  clusterIP:
  loadBalancerIP:


resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

env: []

externalSecrets:
  enabled: true
  items:
  - name: mariadb-secret
    secretStoreRef: onepassword-connect
    data:
    - secretKey: rootPassword
      remoteKey: mariadb-root-password
    - secretKey: dbPassword
      remoteKey: mariadb-ha-password
    templateData:
      rootPassword:
        value: rootPassword
        isSecret: true
      dbUser:
        value: hadbuser
        isSecret: false
      dbPassword:
        value: dbPassword
        isSecret: true
      dbName:
        value: homeassistant
        isSecret: false

settings:
  existingSecret: mariadb-secret
  rootPassword:
    secretKey: rootPassword
  allowEmptyRootPassword: false
  skipTZInfo: false
  arguments:
  - --character-set-server=utf8mb4
  - --collation-server=utf8mb4_unicode_ci

userDatabase:
  name:
    secretKey: dbName
  existingSecret: mariadb-secret
  user:
    secretKey: dbUser
  password:
    secretKey: dbPassword

storage:
  requestedSize: 8Gi
  accessModes:
  - ReadWriteOnce
  className: "longhorn"
  volumeName: "db-volume"
  keepPvc: true
