image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.8.1
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Amsterdam

service:
  main:
    ports:
      http:
        port: 8123

ingress:
  main:
    enabled: false

securityContext:
  privileged:

hostNetwork: true

dnsPolicy: ClusterFirstWithHostNet

persistence:
  config:
    enabled: true
    size: 10Gi

  usb:
    enabled: false
    type: hostPath
    hostPath: /path/to/device

metrics:
  enabled: false
  serviceMonitor:
    interval: 1m
    scrapeTimeout: 30s
    labels: {}
  prometheusRule:
    enabled: false
    labels: {}
    rules: []

addons:
  codeserver:
    enabled: true
    args:
    - --auth
    - none
    - --user-data-dir
    - /data/config/.vscode
    volumeMounts:
    - name: config
      mountPath: /data/config

httproutes:
- enabled: true
  name: ha-httproute
  namespace: home-assistant
  hostname: ha.app.damman.tech
  path: /
  gateway:
    name: app-gateway
    namespace: kube-system
    sectionName: app-https-listener
  backend:
    name: home-assistant
    port: 8123

- enabled: true
  name: codeserver-httproute
  namespace: home-assistant
  hostname: codeserver.app.damman.tech
  path: /
  gateway:
    name: app-gateway
    namespace: kube-system
    sectionName: app-https-listener
  backend:
    name: home-assistant-codeserver
    port: 12321
