image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.5.1
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Amsterdam

service:
  main:
    ports:
      http:
        port: 8123

ingress:
  main:
    enabled: false

securityContext:
  privileged:


hostNetwork: true

dnsPolicy: ClusterFirstWithHostNet

persistence:
  config:
    enabled: true
    size: 10Gi

  usb:
    enabled: false
    type: hostPath
    hostPath: /path/to/device

metrics:
  enabled: false
  serviceMonitor:
    interval: 1m
    scrapeTimeout: 30s
    labels: {}
  prometheusRule:
    enabled: false
    labels: {}
    rules: []

addons:
  codeserver:
    enabled: true
    args:
    - --auth
    - none
    - --user-data-dir
    - /data/config/.vscode
    volumeMounts:
    - name: config
      mountPath: /data/config
