replicaCount: 1

image:
  repository: ghcr.io/home-assistant/home-assistant
  pullPolicy: IfNotPresent
  tag: ""

hostNetwork: true

service:
  type: ClusterIP
  port: 8080
  annotations: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ""
  existingVolume: ""
  annotations: {}
  matchLabels: {}
  matchExpressions: {}

configuration:
  enabled: true

addons:
  codeserver:
    enabled: true
    image:
      repository: ghcr.io/coder/code-server
      pullPolicy: IfNotPresent
      tag: "4.99.2"
