image:
  repository: koenkk/zigbee2mqtt
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecrets: []

zigbee2mqtt:
  timezone: Europe/Amsterdam
  frontend:
    port: 8080

statefulset:
  replicas: 1
  dnsPolicy: ClusterFirst
  affinity: {}
  nodeSelector: {}
  tolerations: []
  securityContext: {}
  lifecycle: {}
  command: []
  resources: {}
  volumeMounts: []
  volumes: []
  secrets:
    name: "" # wordt niet gebruikt, want config is via external secret als secret volume
  storage:
    enabled: true
    size: 1Gi
    storageClassName: longhorn

secretesMigratorContainer:
  repository: mikefarah/yq
  tag: v4.40.5
  securityContext: {}

externalSecrets:
  enabled: true
  items:
  - name: zigbee2mqtt-config
    secretStoreRef: onepassword-connect
    data:
    - remoteKey: zigbee2mqtt-config
      secretKey: configuration.yaml
    templateData:
      configuration.yaml:
        value: configuration.yaml
        isSecret: true

service:
  annotations: {}
  type: ClusterIP
  port: 8080

httproutes:
- enabled: true
  name: zigbee-httproute
  namespace: zigbee2mqtt
  hostname: zigbee.app.damman.tech
  path: /
  gateway:
    name: app-gateway
    namespace: kube-system
    sectionName: app-https-listener
  backend:
    name: zigbee2mqtt
    port: 8080
