---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-config
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        configuration.yaml: '{{ `{{ .config }}` }}'
  data:
    - secretKey: config
      remoteRef:
        key: zigbee2mqtt-config
        property: configuration.yaml
