{{- /*
Template: ExternalSecret voor zigbee2mqtt config
*/ -}}
{{- define "zigbee2mqtt.external-secret" -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-config
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        configuration.yaml: '{{ `{{ .configuration.yaml }}` }}'
  data:
  - secretKey: configuration.yaml
    remoteRef:
      key: zigbee2mqtt-config
{{- end }}
