apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "zigbee2mqtt.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "zigbee2mqtt.labels" . | nindent 8 }}
        app: {{ include "zigbee2mqtt.fullname" . }}
    spec:
      dnsPolicy: {{ .Values.statefulset.dnsPolicy }}
      containers:
        - name: zigbee2mqtt
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.zigbee2mqtt.timezone }}
          ports:
            - containerPort: {{ .Values.zigbee2mqtt.frontend.port }}
              name: web
              protocol: TCP
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      initContainers:
        - name: copy-config
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - cp /app/readonly/configuration.yaml /app/data/configuration.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /app/readonly
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: config-volume
          secret:
            secretName: zigbee2mqtt-config
        {{- if not .Values.statefulset.storage.enabled }}
        - name: data-volume
          emptyDir: {}
        {{- end }}
  {{- if .Values.statefulset.storage.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.statefulset.storage.storageClassName | quote }}
        {{- if .Values.statefulset.storage.existingVolume }}
        volumeName: {{ .Values.statefulset.storage.existingVolume | quote }}
        {{- end }}
        {{- if or (not (empty .Values.statefulset.storage.matchLabels)) (not (empty .Values.statefulset.storage.matchExpressions)) }}
        selector:
          {{- if not (empty .Values.statefulset.storage.matchLabels) }}
          matchLabels:
            {{ toYaml .Values.statefulset.storage.matchLabels | indent 12 }}
          {{- end }}
          {{- if not (empty .Values.statefulset.storage.matchExpressions) }}
          matchExpressions:
            {{ toYaml .Values.statefulset.storage.matchExpressions | indent 12 }}
          {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.statefulset.storage.size | quote }}
  {{- end }}
