apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "zigbee2mqtt.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "zigbee2mqtt.labels" . | nindent 8 }}
        app: {{ include "zigbee2mqtt.fullname" . }}
    spec:
      dnsPolicy: {{ .Values.statefulset.dnsPolicy }}
      containers:
        - name: zigbee2mqtt
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.zigbee2mqtt.timezone }}
          ports:
            - containerPort: {{ .Values.zigbee2mqtt.frontend.port }}
              name: web
              protocol: TCP
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      initContainers:
        - name: copy-config
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - cp /app/readonly/configuration.yaml /app/data/configuration.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /app/readonly
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: config-volume
          secret:
            secretName: zigbee2mqtt-config
        - name: data-volume
          emptyDir: {}
