---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "zigbee2mqtt.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "zigbee2mqtt.fullname" . }}
    spec:
      containers:
        - name: zigbee2mqtt
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: config-volume
              mountPath: /app/data/configuration.yaml
              subPath: configuration.yaml
      volumes:
        - name: config-volume
          secret:
            secretName: zigbee2mqtt-config
---
{{ include "zigbee2mqtt.external-secret" . }}
